// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InsertDataToGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertDataToGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201801042041528_InsertDataToGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
